### ISSUE TITLE
好像坏掉了= =

### ISSUE THREAD

**Issue by panda2134** [YuhangQ/bzojChecker#2]
不断exit with errorcode 2
我写了个watchdog不断重启也不管用，一启动就崩

**Comment by panda2134** [comment]
```log
BZOJ 爬虫程序 v1.2
检查网络状态...√
检查配置文件...√
配置邮件服务...√
载入用户列表...√
处理用户信息...panic: runtime error: index out of range

goroutine 1 [running]:
bzojChecker/bzoj.GetSubmit(0xc4203dc0d0, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/YuhangQ/go/src/bzojChecker/bzoj/bzoj.go:43 +0x355
bzojChecker/checker.LoadRunID(0xc4200b2000, 0x7, 0x8, 0x15, 0x0)
	/Users/YuhangQ/go/src/bzojChecker/checker/submitChecker.go:18 +0x1c8
main.main()
	/Users/YuhangQ/go/src/bzojChecker/main.go:75 +0x873

```
